# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9e440658aa0607eeca4618c2056cdc62d0f07910e6872bf8300e41d89b473140909ee8a7f84d5655172a64dcf84da4bcc8bcd0e8498d97550ecb077865bce37

test:
  secret_key_base: d59e3853ce4df2a24434e40e46bdfeda0d37a6bf92a5dda5902205b606e318fb3d1b61ae3fa8130df029d3741c358b64a7ba7d09eeba681de6e041fcc65bfb59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
